### ISSUE TITLE
Failed to parse download count from github at low numbers

### ISSUE THREAD

**Issue by strayge** [WowUp/WowUp#511]
**Describe the bug**
Failed to parse download count from github at low numbers (below 1k?).

**To Reproduce**
1. Install from URL
2. `https://github.com/ketho-wow/KethoInstanceTimer/`
3. Import
4. Not showed download count (also non-stop spamming errors at console)

**Expected behavior**
Show download count even for low popular addons.

**Screenshots**
![image](https://user-images.githubusercontent.com/2664578/99915853-50524a00-2d17-11eb-88dd-15bbd34220ff.png)

**Desktop (please complete the following information):**
 - Windows 10
 - v2.0.0-rc.3

**Comment by jliddev** [comment]
This should be fixed

**Comment by strayge** [comment]
for https://github.com/strayge/wow-addon-test it still fails at `getDownloadCountParams`

**Comment by strayge** [comment]
increased download count for `https://github.com/ketho-wow/KethoInstanceTimer`
so can test on it

**Comment by jliddev** [comment]
OK for reals this time

**Comment by strayge** [comment]
ok, now fixed
