### ISSUE TITLE
All Curse addons show as having updates

### ISSUE THREAD

**Issue by cremor** [WowUp/WowUp#648]
**Describe the bug**
After updating to v2.1.0-beta.15 all my installed addons from Curse show as having updates available.

**To Reproduce**
1. Update from v2.1.0-beta.14 to v2.1.0-beta.15
2. Check the installed addons list.

**Expected behavior**
Addons should not show as having updates if they don't really have one.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 84.0.1 (why is this relevant?)
 - Version v2.1.0-beta.15

**Additional context**
It seems like this bug not just happens after the update. I later installed an addon from Curse (already with beta 15) and then restarted WowUp. It then showed the just installed addon as having an update even though it didn't - just like it did with all addons after the client update.

**Comment by CDAGaming** [comment]
Seeing this same issue!

**Comment by jliddev** [comment]
This will be resolved next build

**Comment by jliddev** [comment]
These should have been resolved by beta 16, can anyone verify?

**Comment by cremor** [comment]
The update from beta 15 to 16 didn't show any unexpected addons as having updates. But I can still reproduce the following with beta 16:

1. Install WeakAuras from Curse.
2. Restart WowUp
3. It shows WeakAuras as having an update although it is already up to date.

**Comment by CDAGaming** [comment]
I can check shortly.

**Comment by CDAGaming** [comment]
Beta 16 from Beta 15 did fix existing addons, but It seems the old schema is still applying towards newly installed addons

**Comment by jliddev** [comment]
Ah i see the issue
